name: Deploy to Amazon ECS

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest

defaults:
  run:
    shell: bash

jobs:
  run_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run unit test"

  login_aws_ecr:
    name: Login, Build, Deploy to Amazon ECR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - run: echo "🎉 login to Amazon ECR success"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest .
<<<<<<< HEAD
          docker push 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest
=======
          docker push 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest

      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami

      # env:
      # SSH_USER: ${{ secrets.STAGING_SSH_USER }}
      # SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      # SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      # - name: Stop the server
      #   run: ssh dev 'docker stop $(docker ps -a -q)'

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      # - run: echo "🎉 login to Amazon ECR success"

      # - name: Pull new image
      #   run: docker pull 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest

      # - name: Start the server
      #   if: ${{ always() }}
      #   run: docker run -it -p 8080:80 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest
>>>>>>> 📦  test 🐱
