name: Run unit test

on: 
  pull_request:
    branches:
        - masters

defaults:
  run:
    shell: bash

jobs:
  run_test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest .
          docker push 522027946869.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-test:latest